steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the Angular app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--', '--configuration=production']

  # Step 3: Build a Docker image for deployment
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/angular-app', '.']

  # Step 4: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/angular-app']

  # Step 5: Deploy to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'angular-app'
      - '--image=gcr.io/$PROJECT_ID/angular-app'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY  # Fixes the logging issue
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: 900s  # Set timeout to 15 minutes

images:
  - 'gcr.io/$PROJECT_ID/angular-app'

